### ISSUE TITLE
Failt to generate IOS build on phonegap 

### ISSUE THREAD

**Issue by gabyawadcsp** [bykof/cordova-plugin-webserver#36]
Error - Plugin error (you probably need to remove plugin files from your app): //github.com/bykof/cordova-plugin-webserver --nohooks=.": Fetching plugin "https://github.com/bykof/cordova-plugin-webserver" via git clone Using shallow clone Repository "https://github.com/bykof/cordova-plugin-webserver" checked out to git ref "master" at "64f3e3a". Installing "cordova-plugin-webserver" at "1.1.0" for ios Fetching plugin "cordova-plugin-add-swift-support@2.0.2" via npm Installing "cordova-plugin-add-swift-support" at "2.0.2" for ios Failed to install 'cordova-plugin-webserver': Error: pod: Command failed with exit code 1 at ChildProcess.whenDone (/private/tmp/gimlet/3428228/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23) at ChildProcess.emit (events.js:182:13) at maybeClose (internal/child_process.js:962:16) at Socket.stream.socket.on (internal/child_process.js:381:11) at Socket.emit (events.js:182:13) at Pipe._handle.close (net.js:611:12)

**Comment by boedy** [comment]
`cordova-plugin-add-swift-support@2.0.2` is quite new. Might need to update your local pod repository. Running the following command in your `platforms/ios` dir might do the trick:

> pod install --repo-update
