### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by JuneTwooo** [bykof/cordova-plugin-webserver#44]
Hi, thank you for your amazing work !

Sometime, webserver stop working, this is the logcat :

[ 09-13 16:35:49.614 19835:25848 E/fi.iki.elonen.NanoHTTPD ]
Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1443)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1435)
	at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

[ 09-13 16:35:49.616 19835:25849 E/fi.iki.elonen.NanoHTTPD ]
Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1443)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1435)
	at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

[ 09-13 16:35:49.617 24723:25795 D/ProtoHookJ ]
Responsecode of POST: 200

[ 09-13 16:35:49.620 19835:25850 E/fi.iki.elonen.NanoHTTPD ]
Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1443)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1435)
	at java.util.zip.GZIPOutputStream.writeHeader(GZIPOutputStream.java:182)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:94)
	at java.util.zip.GZIPOutputStream.<init>(GZIPOutputStream.java:109)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1663)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

[ 09-13 16:35:49.622 19835:25851 E/fi.iki.elonen.NanoHTTPD ]
Could not send response to the client
java.net.SocketException: Broken pipe
	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at fi.iki.elonen.NanoHTTPD$Response$ChunkedOutputStream.write(NanoHTTPD.java:1443)
	at java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:164)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectEncoding(NanoHTTPD.java:1665)
	at fi.iki.elonen.NanoHTTPD$Response.sendBodyWithCorrectTransferAndEncoding(NanoHTTPD.java:1654)
	at fi.iki.elonen.NanoHTTPD$Response.send(NanoHTTPD.java:1624)
	at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:957)
	at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
	at java.lang.Thread.run(Thread.java:764)

Have you got an idea ?

**Comment by abdalladimes** [comment]
Same Here, Im facing the same issue, did you find any solution? or even why this is happening ?
